### ISSUE TITLE
[![CDATA xml tags error. "overloaded method value domBindingSeq with alternatives:"

### ISSUE THREAD

**Issue by baram204** [ThoughtWorksInc/Binding.scala#58] opened 2017-07-28 05:27 UTC
scalafiddle ok.

https://scalafiddle.io/sf/Sc0RmDj/3

but. desktop spit out errors.

code 
```scala
  @dom def inlineStyle = {
    <section>
      <style>
        <![CDATA[
         .highlight {background-color:gold}
         ]]>
      </style>
      <p> Binding.scala. easy to use.
      </p>
    </section>
  }
```

sbt environment.
```
scala 2.12
scalajs 0.6.15 
libraryDependencies += "com.thoughtworks.binding" %%% "binding" % "latest.release"
libraryDependencies += "com.thoughtworks.binding" %%% "dom" % "latest.release"
libraryDependencies += "com.thoughtworks.binding" %%% "futurebinding" % "latest.release"
libraryDependencies += "com.thoughtworks.binding" %%% "jspromisebinding" % "latest.release"
```

error message

```bash
[error] /Users/baram204/IdeaProjects/learningPixi/src/main/scala/binding/L07_XHTMLliterals.scala:39: overloaded method value domBindingSeq with alternatives:
[error]   (text: String)com.thoughtworks.binding.Binding.Constants[org.scalajs.dom.raw.Text] <and>
[error]   (node: org.scalajs.dom.raw.Node)com.thoughtworks.binding.Binding.Constants[org.scalajs.dom.raw.Node] <and>
[error]   (seq: Seq[org.scalajs.dom.raw.Node])com.thoughtworks.binding.Binding.Constants[org.scalajs.dom.raw.Node] <and>
[error]   (bindingSeq: com.thoughtworks.binding.Binding.BindingSeq[org.scalajs.dom.raw.Node])com.thoughtworks.binding.Binding.BindingSeq[org.scalajs.dom.raw.Node]
[error]  cannot be applied to (scala.xml.PCData)
[error]         <![CDATA[
[error]                  ^

```

**Comment by Atry** [comment] 2017-07-28 05:31
Looks like a duplicate of https://github.com/ThoughtWorksInc/Binding.scala/issues/30

**Comment by Atry** [comment] 2017-07-28 05:33
Did you add the Scalac flag `-Xxml:-coalescing`?
The flag is not supported at the moment.

**Comment by baram204** [comment] 2017-07-28 05:44
I didn't.

so I put flag to build.sbt.

```
scalacOptions += "-Xxml:-coalescing"
```

and still got same error.

**Comment by Atry** [comment] 2017-07-28 06:30
I mean `-Xxml:-coalescing` will cause the error. You may want to remove it.

**Comment by baram204** [comment] 2017-07-28 06:34
Ok. I got it.

**Comment by 0x7fh** [comment] 2017-08-26 09:47
Hint: I had the same problem under Scala 2.12.3 and Scala-JS 0.6.19. I had to _enable_ coalescing explicitly with `-Xxml:coalescing` to get rid of the error.

**Comment by Atry** [comment] 2018-03-28 17:10
@0x7fh Maybe there is another sbt plug-in who introduced the  `-Xxml:-coalescing` flag.

**Closed** 2018-08-18 09:09 UTC
